import React from 'react';
import { ArrowUpRight, ArrowRight, Phone, Mail, MapPin, MessageCircle, X, Plus, HeartHandshake, BookOpen, Clock3, Facebook, Instagram, Music2, Globe } from 'lucide-react';
import { images, googleLink, whatsappLink, faqs, contactEmail, socialLinks } from './content';

export function CallToAction(){return <section className="cta-section"><div><span className="eyebrow">YOUR NEXT CHAPTER STARTS HERE</span><h2>You bring the heart.<br/>We help you build <em>the skills.</em></h2><p>Let’s take the first step towards your future in care, together.</p></div><a className="button light-button" href="/contact.html">Start your journey <ArrowUpRight size={18}/></a></section>}

export function Footer(){const socialItems=[{label:'Facebook',href:socialLinks.facebook,Icon:Facebook},{label:'Instagram',href:socialLinks.instagram,Icon:Instagram},{label:'TikTok',href:socialLinks.tiktok,Icon:Music2},{label:'Google',href:socialLinks.google,Icon:Globe}]; return <footer><div className="footer-grid"><div className="footer-brand"><img src={images+'logo.webp'} alt="Happy Valley Academy" loading="lazy"/><p>Learn today. Care tomorrow.<br/>Care training with people at its heart.</p></div><div><h4>EXPLORE</h4><a href="/">Home</a><a href="/about.html">Our Academy</a><a href="/courses.html">Our Courses</a><a href="/contact.html">Contact Us</a></div><div className="footer-path"><h4>FIND YOUR PATH</h4><a href="/courses.html#elderly-care">Elderly Care</a><a href="/courses.html#first-aid">First Aid Level 101</a><a href="/courses.html#baby-care">Baby Care / Nanny</a><a href="/courses.html#package">All-course package</a><div className="social-links">{socialItems.map(({label,href,Icon})=><a key={label} href={href} target={href!== '#' ? '_blank' : undefined} rel={href !== '#' ? 'noreferrer' : undefined} aria-label={label} title={label}><Icon size={16}/></a>)}</div></div><div className="footer-contact"><h4>LET’S CONNECT</h4><a href="tel:+27611173163">061 117 3163</a><a href="tel:+27839929153">083 992 9153</a><a href="tel:+27816736289">081 673 6289</a><a href={'mailto:'+contactEmail}>{contactEmail}</a></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Happy Valley Academy. All rights reserved.</span><span>Made for a future of care.</span></div></footer>}

export function WhatsAppWidget(){const[open,setOpen]=React.useState(false); const panelRef=React.useRef(null); const buttonRef=React.useRef(null); React.useEffect(()=>{if(open) panelRef.current?.focus();},[open]); function close(){setOpen(false);buttonRef.current?.focus();} return <div className="whatsapp-widget">{open&&<section className="chat-panel" ref={panelRef} tabIndex={-1} aria-label="WhatsApp enquiry" onKeyDown={e=>{if(e.key==='Escape')close();}}><div className="chat-heading"><HeartHandshake size={25}/><div><strong>Happy Valley Academy</strong><span>Let’s talk about your future</span></div><button onClick={close} aria-label="Close WhatsApp panel"><X size={18}/></button></div><div className="chat-body"><p>Hello! Ready to take the next step?<br/>Ask us about courses, fees or registration.</p><div className="chat-actions"><a href={whatsappLink()} target="_blank" rel="noreferrer" className="button green-button">WhatsApp Inquiry <MessageCircle size={16}/></a><a href={'mailto:'+contactEmail} className="button light-button">Email Inquiry <Mail size={16}/></a></div></div></section>}<button ref={buttonRef} className="whatsapp-float" aria-expanded={open} aria-label={open?'Close WhatsApp enquiry':'Open WhatsApp enquiry'} onClick={()=>open?close():setOpen(true)}>{open?<X size={23}/>:<MessageCircle size={23}/>}<span>{open?'Close':'Let’s chat'}</span></button></div>}

export function PageIntro({label,title,accent,description}){return <section className="page-intro"><div className="breadcrumb"><a href="/">Home</a><span>/</span><span>{label}</span></div><span className="eyebrow">HAPPY VALLEY ACADEMY</span><h1>{title} <em>{accent}</em></h1><p>{description}</p></section>}

export function Faq(){return <section className="section faq-section"><div><span className="eyebrow">A LITTLE CLARITY</span><h2>Your questions,<br/><em>answered.</em></h2><p>We’re here to help you find your next step.</p><a className="text-link" href="/contact.html">Ask us something else <ArrowUpRight size={17}/></a></div><div className="faq-list">{faqs.map(([q,a])=><details key={q}><summary>{q}<Plus size={17}/></summary><p>{a}</p></details>)}</div></section>}

export function Journey(){return <section className="section journey"><div className="section-heading"><div><span className="eyebrow">FROM POSSIBILITY TO PRACTICE</span><h2>A simple start to <em>something meaningful.</em></h2></div></div><div className="journey-grid">{[['01','Find your course','Choose elderly care, first aid, baby care — or explore all three.'],['02','Let’s have a conversation','Contact us to confirm dates, requirements and registration details.'],['03','Learn. Practise. Grow.','Build your knowledge with theory and practical learning.']].map(([n,title,text])=><div key={n}><span className="step-number">{n}</span><h3>{title}</h3><p>{text}</p></div>)}</div></section>}

export function HomeMore(){return <><div className="registration-note"><span>ADDITIONAL REGISTRATION <strong>R500</strong></span><span>Explore more possibilities. <a href="/courses.html#package">All three courses: R4,000 + R500 registration <ArrowRight size={15}/></a></span></div><section className="section academy-story"><div className="story-photo"><img src={images+'IMG-20260916-WA0032.webp'} alt="Happy Valley Academy team wearing branded pink and blue uniforms" loading="lazy"/><div className="story-caption"><HeartHandshake size={20}/> PEOPLE. PURPOSE. POSSIBILITY.</div></div><div className="story-copy"><span className="eyebrow">WELCOME TO HAPPY VALLEY</span><h2>Behind every great carer,<br/>there’s a <em>place to begin.</em></h2><p>Care is personal. So is your journey into it. At Happy Valley Academy, we bring learning and compassion together through courses in elderly care, first aid and baby care.</p><p>With theory, practical learning and placements for practicals, your next chapter begins with skills you can put into practice.</p><div className="story-points"><span><BookOpen size={18}/> Knowledge with a purpose</span><span><HeartHandshake size={18}/> Compassion at the centre</span></div><a className="text-link" href="/about.html">Get to know our academy <ArrowUpRight size={17}/></a></div></section><section className="care-banner"><img src={images+'workplace-images-v2/work-05-childcare-v2.webp'} alt="A caregiver guiding children through a creative activity" loading="lazy"/><div><span className="eyebrow">THE DIFFERENCE STARTS WITH YOU</span><h2>A skill learned.<br/>A life <em>touched.</em></h2><p>From the smallest moments to the biggest responsibilities,<br/>care has the power to change someone’s day.</p><a href="/courses.html" className="button light-button">Find your course <ArrowUpRight size={17}/></a></div></section><Journey/><CallToAction/></>}
