export const images = '/images/';
export const googleLink = 'https://www.google.com/search?hl=en-GB&gl=ZA&kgmid=%2Fg%2F11zyn27p1j&q=Happy%20Valley%20Academy';
export const whatsappLink = (message = 'Hello Happy Valley Academy, I would like to enquire about your courses.') => 'https://wa.me/27611173163?text=' + encodeURIComponent(message);
export const courses = [
  { id: 'elderly-care', name: 'Elderly Care', price: 2500, image: 'workplace-images-v2/work-02-mobility-support-v2.webp', training: 'academy-images/class-01-elderly-care.webp', label: 'COMPASSION IN EVERYDAY MOMENTS', description: 'Bring comfort, dignity and companionship to those who need it most.', detail: 'Caring for older people begins with understanding, patience and respect. Explore elderly care through a combination of theory and practical learning, and take your first step towards a meaningful future in care.', focus: ['Compassionate support for older people', 'Care that respects dignity and independence', 'Theory supported by practical experience'] },
  { id: 'first-aid', name: 'First Aid Level 101', price: 1700, image: 'workplace-images-v2/work-03-first-aid-v2.webp', training: 'academy-images/class-02-cpr.webp', label: 'CONFIDENCE WHEN IT MATTERS', description: 'Build the confidence to respond with care when every moment matters.', detail: 'Develop your understanding of first aid in a learning environment that brings theory and practice together. Speak with our team about the course content, practical sessions and the next available intake.', focus: ['An introduction to first aid', 'Practical learning alongside theory', 'A thoughtful, confident approach to helping others'] },
  { id: 'baby-care', name: 'Baby Care / Nanny', price: 1000, image: 'workplace-images-v2/work-04-infant-care-v2.webp', training: 'academy-images/class-04-baby-care.webp', label: 'LITTLE LIVES. LASTING IMPACT.', description: 'Nurture little lives with patient, thoughtful and attentive care.', detail: 'Turn your love for children into purposeful learning. Our baby care and nanny course combines theory with practical experience to help you begin your journey in caring for little ones.', focus: ['A caring approach to babies and children', 'Patient and attentive childcare', 'Theory and practical learning combined'] },
];
export const money = value => 'R' + value.toLocaleString('en-ZA');
export const faqs = [
  ['How long are the courses?', 'The academy advertises a three-month duration for all courses, including theory and practicals. Please contact our team for the timetable and the next intake dates.'],
  ['Is practical training included?', 'Yes. The academy arranges placements for practicals, so learning extends beyond the classroom. Contact us to discuss how practical placement works for your chosen course.'],
  ['How much does registration cost?', 'The advertised registration fee is R500. Course fees are R2,500 for Elderly Care, R1,700 for First Aid Level 101 and R1,000 for Baby Care / Nanny. All three courses are advertised at R4,000. Please confirm whether registration is additional to your selected package before paying.'],
  ['How do I enrol?', 'Send us a WhatsApp message or call one of our contact numbers. Our team can confirm entry requirements, dates, payment details and the documents needed to register.'],
  ['Can I take all three courses?', 'Yes. The flyer offers all three courses for R4,000. Ask our team about the combined course schedule and registration arrangements.'],
];
